<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\Authentication\Validators\" />
    <Folder Include="Features\Events\Delete\" />
    <Folder Include="Features\Events\Update\" />
    <Folder Include="Features\Itinerary\Create\" />
    <Folder Include="Features\Itinerary\GetById\" />
    <Folder Include="Features\Itinerary\Delete\" />
    <Folder Include="Features\Itinerary\update\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.3.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Tourism.Domain.csproj" />
  </ItemGroup>

</Project>
