// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tourism.Infrastructure.Persistence;

#nullable disable

namespace Tourism.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260917102708_decimalForStarRating")]
    partial class decimalForStarRating
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DTourism.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Tourism.Domain.Entities.Attraction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BookingUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageGallery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Attractions");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.BlogPost", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Featured")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReadTime")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.BookingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Guests")
                        .HasColumnType("int");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialRequests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredContactMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.Hotel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageGallery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("RoomTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StarRating")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.Itinerary", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExcludedServices")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Highlights")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncludedServices")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Itineraries");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.ItineraryDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accommodation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Activities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItineraryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Meals")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryId");

                    b.ToTable("ItineraryDays");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.NewsletterSubscription", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Preferences")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubscribeDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Email");

                    b.ToTable("NewsletterSubscriptions");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.Photographer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Social")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialties")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Photographers");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.Restaurant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageGallery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("MenuUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("Specialties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.ServiceItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("AcceptsInsurance")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CommentsCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeaturesAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HasDelivery")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Is24h")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsEmergency")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Specialty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialtyAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.SouvenirCategory", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("SouvenirCategories");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.SouvenirProduct", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Handmade")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("SouvenirProducts");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.SouvenirShop", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("AcceptsCreditCard")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HasDelivery")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasOnlineStore")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningHoursAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<int?>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("Specialties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialtiesAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SouvenirShops");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.TourGuide", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Social")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TourGuides");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.TourismEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TicketPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.TourismInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TourismInfos");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.VisitorInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VisitorInfos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DTourism.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DTourism.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DTourism.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DTourism.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tourism.Domain.Entities.Attraction", b =>
                {
                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Category", b1 =>
                        {
                            b1.Property<string>("AttractionId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AttractionId");

                            b1.ToTable("Attractions");

                            b1.WithOwner()
                                .HasForeignKey("AttractionId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<string>("AttractionId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AttractionId");

                            b1.ToTable("Attractions");

                            b1.WithOwner()
                                .HasForeignKey("AttractionId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "HistoricalPeriod", b1 =>
                        {
                            b1.Property<string>("AttractionId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AttractionId");

                            b1.ToTable("Attractions");

                            b1.WithOwner()
                                .HasForeignKey("AttractionId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<string>("AttractionId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AttractionId");

                            b1.ToTable("Attractions");

                            b1.WithOwner()
                                .HasForeignKey("AttractionId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "OpeningHours", b1 =>
                        {
                            b1.Property<string>("AttractionId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AttractionId");

                            b1.ToTable("Attractions");

                            b1.WithOwner()
                                .HasForeignKey("AttractionId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Significance", b1 =>
                        {
                            b1.Property<string>("AttractionId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AttractionId");

                            b1.ToTable("Attractions");

                            b1.WithOwner()
                                .HasForeignKey("AttractionId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "TicketPrice", b1 =>
                        {
                            b1.Property<string>("AttractionId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AttractionId");

                            b1.ToTable("Attractions");

                            b1.WithOwner()
                                .HasForeignKey("AttractionId");
                        });

                    b.Navigation("Category")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("HistoricalPeriod");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("OpeningHours")
                        .IsRequired();

                    b.Navigation("Significance");

                    b.Navigation("TicketPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("Tourism.Domain.Entities.BlogPost", b =>
                {
                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Author", b1 =>
                        {
                            b1.Property<string>("BlogPostId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BlogPostId");

                            b1.ToTable("BlogPosts");

                            b1.WithOwner()
                                .HasForeignKey("BlogPostId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Category", b1 =>
                        {
                            b1.Property<string>("BlogPostId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BlogPostId");

                            b1.ToTable("BlogPosts");

                            b1.WithOwner()
                                .HasForeignKey("BlogPostId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Content", b1 =>
                        {
                            b1.Property<string>("BlogPostId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BlogPostId");

                            b1.ToTable("BlogPosts");

                            b1.WithOwner()
                                .HasForeignKey("BlogPostId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Excerpt", b1 =>
                        {
                            b1.Property<string>("BlogPostId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BlogPostId");

                            b1.ToTable("BlogPosts");

                            b1.WithOwner()
                                .HasForeignKey("BlogPostId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<string>("BlogPostId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BlogPostId");

                            b1.ToTable("BlogPosts");

                            b1.WithOwner()
                                .HasForeignKey("BlogPostId");
                        });

                    b.Navigation("Author")
                        .IsRequired();

                    b.Navigation("Category")
                        .IsRequired();

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("Excerpt")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Tourism.Domain.Entities.Hotel", b =>
                {
                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<string>("HotelId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("HotelId");

                            b1.ToTable("Hotels");

                            b1.WithOwner()
                                .HasForeignKey("HotelId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<string>("HotelId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("HotelId");

                            b1.ToTable("Hotels");

                            b1.WithOwner()
                                .HasForeignKey("HotelId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "PriceRange", b1 =>
                        {
                            b1.Property<string>("HotelId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("HotelId");

                            b1.ToTable("Hotels");

                            b1.WithOwner()
                                .HasForeignKey("HotelId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("PriceRange")
                        .IsRequired();
                });

            modelBuilder.Entity("Tourism.Domain.Entities.ItineraryDay", b =>
                {
                    b.HasOne("Tourism.Domain.Entities.Itinerary", "Itinerary")
                        .WithMany("DayByDay")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Itinerary");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.Photographer", b =>
                {
                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Bio", b1 =>
                        {
                            b1.Property<string>("PhotographerId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PhotographerId");

                            b1.ToTable("Photographers");

                            b1.WithOwner()
                                .HasForeignKey("PhotographerId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Email", b1 =>
                        {
                            b1.Property<string>("PhotographerId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PhotographerId");

                            b1.ToTable("Photographers");

                            b1.WithOwner()
                                .HasForeignKey("PhotographerId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<string>("PhotographerId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PhotographerId");

                            b1.ToTable("Photographers");

                            b1.WithOwner()
                                .HasForeignKey("PhotographerId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Phone", b1 =>
                        {
                            b1.Property<string>("PhotographerId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PhotographerId");

                            b1.ToTable("Photographers");

                            b1.WithOwner()
                                .HasForeignKey("PhotographerId");
                        });

                    b.Navigation("Bio");

                    b.Navigation("Email");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.Restaurant", b =>
                {
                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Center", b1 =>
                        {
                            b1.Property<string>("RestaurantId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("Restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "CuisineType", b1 =>
                        {
                            b1.Property<string>("RestaurantId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("Restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<string>("RestaurantId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("Restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<string>("RestaurantId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("Restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "OpeningHours", b1 =>
                        {
                            b1.Property<string>("RestaurantId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("Restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "PriceRange", b1 =>
                        {
                            b1.Property<string>("RestaurantId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("Restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId");
                        });

                    b.Navigation("Center");

                    b.Navigation("CuisineType")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("OpeningHours")
                        .IsRequired();

                    b.Navigation("PriceRange")
                        .IsRequired();
                });

            modelBuilder.Entity("Tourism.Domain.Entities.SouvenirProduct", b =>
                {
                    b.HasOne("Tourism.Domain.Entities.SouvenirShop", "Shop")
                        .WithMany("Products")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.TourGuide", b =>
                {
                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Bio", b1 =>
                        {
                            b1.Property<string>("TourGuideId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TourGuideId");

                            b1.ToTable("TourGuides");

                            b1.WithOwner()
                                .HasForeignKey("TourGuideId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Email", b1 =>
                        {
                            b1.Property<string>("TourGuideId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TourGuideId");

                            b1.ToTable("TourGuides");

                            b1.WithOwner()
                                .HasForeignKey("TourGuideId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<string>("TourGuideId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TourGuideId");

                            b1.ToTable("TourGuides");

                            b1.WithOwner()
                                .HasForeignKey("TourGuideId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Phone", b1 =>
                        {
                            b1.Property<string>("TourGuideId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TourGuideId");

                            b1.ToTable("TourGuides");

                            b1.WithOwner()
                                .HasForeignKey("TourGuideId");
                        });

                    b.Navigation("Bio");

                    b.Navigation("Email");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.TourismEvent", b =>
                {
                    b.OwnsOne("Tourism.Domain.Entities.EventContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<string>("TourismEventId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Phone")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Website")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TourismEventId");

                            b1.ToTable("Events");

                            b1.ToJson("ContactInfo");

                            b1.WithOwner()
                                .HasForeignKey("TourismEventId");
                        });

                    b.Navigation("ContactInfo");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.TourismInfo", b =>
                {
                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "BestTimeToVisit", b1 =>
                        {
                            b1.Property<string>("TourismInfoId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TourismInfoId");

                            b1.ToTable("TourismInfos");

                            b1.WithOwner()
                                .HasForeignKey("TourismInfoId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Climate", b1 =>
                        {
                            b1.Property<string>("TourismInfoId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TourismInfoId");

                            b1.ToTable("TourismInfos");

                            b1.WithOwner()
                                .HasForeignKey("TourismInfoId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Notes", b1 =>
                        {
                            b1.Property<string>("TourismInfoId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TourismInfoId");

                            b1.ToTable("TourismInfos");

                            b1.WithOwner()
                                .HasForeignKey("TourismInfoId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<string>("TourismInfoId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TourismInfoId");

                            b1.ToTable("TourismInfos");

                            b1.WithOwner()
                                .HasForeignKey("TourismInfoId");
                        });

                    b.OwnsOne("Tourism.Domain.Entities.Common.LocalizedText", "WhatToWear", b1 =>
                        {
                            b1.Property<string>("TourismInfoId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TourismInfoId");

                            b1.ToTable("TourismInfos");

                            b1.WithOwner()
                                .HasForeignKey("TourismInfoId");
                        });

                    b.Navigation("BestTimeToVisit")
                        .IsRequired();

                    b.Navigation("Climate")
                        .IsRequired();

                    b.Navigation("Notes");

                    b.Navigation("Title")
                        .IsRequired();

                    b.Navigation("WhatToWear")
                        .IsRequired();
                });

            modelBuilder.Entity("Tourism.Domain.Entities.Itinerary", b =>
                {
                    b.Navigation("DayByDay");
                });

            modelBuilder.Entity("Tourism.Domain.Entities.SouvenirShop", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
